### ISSUE TITLE
Problem when switching to env to production

### ISSUE THREAD

**Issue by emleonstz** [openpesa/php-pesa#31]
I have instantiated the pesa class with valid production credentials and switch it to production but a problem occurs, it fails to generate the session key if I return the sandbox credentials and switch back to sandbox it works fine

**Comment by alphaolomi** [comment]
hello @emleonstz 

how did you fix this?

**Comment by emleonstz** [comment]
it works fine I forgot to change the sandbox PK to openapi PK
