### ISSUE TITLE
Where can we find the official mpesa API documentation

### ISSUE THREAD

**Issue by Munde** [openpesa/php-pesa#5]
I have searched on internet nor on their official website i can find the official documentation so as we can write and write samples to share to the community

**Comment by iamgenes** [comment]
visit openapiportal.m-pesa.com create a developer account and you should be able to access the documentation if you already have an account visit https://openapiportal.m-pesa.com/api-documentation

**Comment by iamgenes** [comment]
> I have searched on the internet nor on their official website I can find the official documentation so as we can write and write samples to share with the community

visit https://openapiportal.m-pesa.com create a developer account and you should be able to access the documentation if you already have an account visit https://openapiportal.m-pesa.com/api-documentation

**Comment by alphaolomi** [comment]
Hello @Munde 

Currently, you can find the  documentation for Pesa SDK for PHP at https://php-pesa.netlify.app/

Documentation for Mpesa OpenAPI is found in the portal 

Get instructions on how to get started with the portal from  https://alphaolomi.hashnode.dev/getting-started-with-mpesa-developer-portal
